ALTER TABLE greenhouse ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE greenhouse ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE greenhouse ADD COLUMN IF NOT EXISTS boundary_geojson TEXT;
